### ISSUE TITLE
JS Bin demo does not work

### ISSUE THREAD

**Issue by kylehoehns** [BerkleyTechnologyServices/slidey#105]
### Description
Clicking the "Toggle Aside" button on the JS Bin demo doesn't trigger a slidey to appear.
https://jsbin.com/mujosep/2/edit?html,js,output

### Expected outcome

Clicking the "Toggle Aside" button should trigger the slidey to appear.

### Browsers Affected

- [x] Chrome
- [ ] Firefox
- [x] Safari 10
- [ ] Safari 9
- [ ] Safari 8
- [ ] Safari 7
- [ ] Edge
- [ ] IE 11

**Comment by nick-woodward** [comment]
Hey @kylehoehns,

Thanks for the heads up, this should now be resolved!
